version: '2'

services:
    golang_gore_shell:
        build:
            context: .
            dockerfile: Dockerfile
        command: sleep 3600
        image: golang_gore_shell
        volumes:
            - .:/opt/src/gore-shell
        privileged: true

        container_name:
            gore_shell

